In [1]:
import numpy as np

In [2]:
da = np.array([3, 5, 7, 9, 12])

In [3]:
type(da)

numpy.ndarray

In [10]:
da.max() # calculate max of array

12

In [11]:
da.min() # calculate min of array

3

In [12]:
da.mean() # calculate mean of array

7.2

In [13]:
da.sum() # calculate sum of array

36

In [14]:
np.median(da)

7.0

#### 0D array

#### 1D array

In [42]:
da = np.array(1977)
print(da)

1977


In [17]:
a = np.array([[2, 4, 2, 8], [2, 3, 1, 8]], float)

In [18]:
np.corrcoef(a)

array([[1.        , 0.98552746],
       [0.98552746, 1.        ]])

In [19]:
x = np.array([2, 4, 2, 8])

In [20]:
y = np.array([2, 3, 1, 8])

In [21]:
np.corrcoef(x, y)

array([[1.        , 0.98552746],
       [0.98552746, 1.        ]])

In [23]:
r = np.corrcoef(x, y)
r

array([[1.        , 0.98552746],
       [0.98552746, 1.        ]])

In [27]:
r[0, 1]

0.9855274566525744

In [28]:
r[1, 0]

0.9855274566525744

In [29]:
r[1, 1]

1.0

In [30]:
import scipy.stats
scipy.stats.pearsonr(x, y)

(0.9855274566525744, 0.014472543347425653)

#### 2D array (i.e., a matrix )

In [45]:
da = np.array([[22, 15, 33], [24, 25, 16], [17, 44, 88]])
da

array([[22, 15, 33],
       [24, 25, 16],
       [17, 44, 88]])

In [47]:
da.shape
print('shape of array:', da.shape)

shape of array: (3, 3)


In [38]:
np.linspace (0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [39]:
np.logspace(0, 1, 10)

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

#### Random numbers

In [57]:
from numpy import random

rn = random.randint(100)

print(rn)

85


In [55]:
da = np.array([[[1, 3, 5], [2, 4, 6]], [[1, 3, 5], [2, 4, 6]]])
da

array([[[1, 3, 5],
        [2, 4, 6]],

       [[1, 3, 5],
        [2, 4, 6]]])

In [64]:
da = np.array([1, 2, 3, 4])

print(da.dtype)

int32


In [60]:
rn = random.rand(3)

print(rn)

[0.78791714 0.84012296 0.15017555]


In [63]:
da + 1

array([2, 3, 4, 5])

In [65]:
da * da

array([ 1,  4,  9, 16])

In [66]:
da

array([1, 2, 3, 4])

In [71]:
a = np.arange(20).reshape(4, 5)

In [72]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
x = np.array([12,np.nan,31,56, 88, np.nan])
x

array([12., nan, 31., 56., 88., nan])

In [74]:
x

array([12., nan, 31., 56., 88., nan])

In [75]:
np.nansum(x)

187.0

In [76]:
np.nanmean(x)

46.75

In [77]:
np.nanmax(x)

88.0

In [80]:
np.nanmin(x)

12.0

In [97]:
t = np.loadtxt('D:\Python\Python_for_Researchers\munich_temperatures_with_bad_data.txt')

In [92]:
np.mean(t[1])

996.697185

In [93]:
np.min(t)

-99.0

In [94]:
np.max(t)

2013.28474

Combined condition:

In [103]:
keep = (t > -30) & (t < 50)
t1 = t[keep]

In [106]:
np.max(t1)

27.6667

In [105]:
np.mean(t1)

8.933222104668378

In [107]:
np.min(t1)

-16.7778

In [108]:
da = np.array([5, 9, 7, 11])
da[0] # first number

5

In [109]:
da[2]

7

In [111]:
da = np.arange(50)
da[1:10]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])